title: Altitude°
author: 
email: altitudeconsultingLLC@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  description

twitter_username: macrod68
github_username:  macrod68

sass:
    style: compressed