title: Altitude°
author: 
email: altitudeconsultingLLC@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bringing analytics consulting to the high country and beyond.

#twitter_username: macrod68
#github_username:  macrod68

sass:
    style: compressed